apiVersion: v1
kind: Service
metadata:
  name: k8s-cicd-service # 서비스 명칭
  labels:
    app: k8s-cicd-devops-project # 서비스에 붙는 레이블, 서비스 자신에 대한 정보이고, selector와는 별개
spec:
  selector:
    app: k8s-cicd-devops-project # k8s-cicd-devops-project라는 레이블을 가진 파드들에 요청을 전달
  type: NodePort
  ports:
    - port: 8080 # 8080포트로 클러스터 내부에서 접속
      targetPort: 8080 # 8080포트로 요청을 전달받을 파드 내부 포트, 서비스가 받은 요청을 파드의 8080포트로 전달
      nodePort: 32000 # 32000포트로 외부에서 접근 가능, localhost:32000 으로 쓰임